/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVista;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import pkgControlador.Control;
import pkgModelo.Auto;
import pkgModelo.HiloMover;

/**
 *
 * @author Marcela
 */
public class FrmAtender extends javax.swing.JFrame {

    Thread hiloMover;
    Control control;

    /**
     * Creates new form FrmAtender
     */
    public FrmAtender() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMecGen = new javax.swing.JButton();
        lblpintura = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblaceite = new javax.swing.JLabel();
        lblalineacio = new javax.swing.JLabel();
        lblbalanceo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        lblelectrico = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnPintura = new javax.swing.JButton();
        btnMecEsp = new javax.swing.JButton();
        lblespecializada = new javax.swing.JLabel();
        lblensayo = new javax.swing.JLabel();
        progressBar_alineacion = new javax.swing.JProgressBar();
        progressBar_balanceo = new javax.swing.JProgressBar();
        progressBar_Frenos = new javax.swing.JProgressBar();
        progressBar_Cambio = new javax.swing.JProgressBar();
        lblareageneral = new javax.swing.JLabel();
        lblareapintura = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        item_registrar = new javax.swing.JMenuItem();
        item_cerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1279, 557));
        setResizable(false);
        getContentPane().setLayout(null);

        btnMecGen.setText("Atender");
        btnMecGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMecGenActionPerformed(evt);
            }
        });
        getContentPane().add(btnMecGen);
        btnMecGen.setBounds(250, 80, 71, 23);

        lblpintura.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblpintura.setText("Servicio Pintura");
        lblpintura.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblpintura.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        getContentPane().add(lblpintura);
        lblpintura.setBounds(810, 100, 110, 90);

        jLabel4.setText("Revisión de frenos");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 150, 150, 80);

        lblaceite.setText("Cambio de aceite");
        lblaceite.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblaceite.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        getContentPane().add(lblaceite);
        lblaceite.setBounds(80, 150, 150, 80);

        lblalineacio.setText("Alineación");
        lblalineacio.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblalineacio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        getContentPane().add(lblalineacio);
        lblalineacio.setBounds(310, 310, 150, 80);

        lblbalanceo.setText("Balanceo");
        lblbalanceo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblbalanceo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        getContentPane().add(lblbalanceo);
        lblbalanceo.setBounds(80, 310, 150, 80);

        jLabel1.setText("Entrada");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 2, true));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(640, 190, 60, 20);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(20, 50, 200, 14);

        lblelectrico.setText(" Servicio revisión y reparación<br>\n del sistema eléctrico");
        lblelectrico.setToolTipText("");
        lblelectrico.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblelectrico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        lblelectrico.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblelectrico);
        lblelectrico.setBounds(900, 380, 110, 90);

        jLabel2.setText("Salida");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1220, 80, 50, 390);

        jLabel3.setText("Servicio reparación de motor");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(750, 380, 110, 90);

        jLabel6.setText("Salida");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(530, 220, 34, 80);

        jLabel5.setText("Entrada");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 2, true));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 430, 50, 30);

        jLabel7.setText("Entrada");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 2, true));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(640, 320, 50, 40);

        jLabel8.setText("Salida");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(950, 190, 70, 20);
        getContentPane().add(jProgressBar2);
        jProgressBar2.setBounds(640, 50, 146, 14);
        getContentPane().add(jProgressBar3);
        jProgressBar3.setBounds(640, 270, 220, 14);

        jLabel9.setText("Recaudo");
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 0), 3, true));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1130, 80, 48, 390);

        jLabel10.setText("Salida");
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(980, 290, 90, 20);

        btnPintura.setText("Atender");
        btnPintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinturaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPintura);
        btnPintura.setBounds(930, 80, 71, 23);

        btnMecEsp.setText("Atender");
        btnMecEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMecEspActionPerformed(evt);
            }
        });
        getContentPane().add(btnMecEsp);
        btnMecEsp.setBounds(860, 300, 71, 23);

        lblespecializada.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblespecializada.setForeground(new java.awt.Color(0, 153, 153));
        lblespecializada.setText("Area Mecanica especializada");
        lblespecializada.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblespecializada.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(lblespecializada);
        lblespecializada.setBounds(640, 290, 430, 180);

        lblensayo.setText("jLabel11");
        getContentPane().add(lblensayo);
        lblensayo.setBounds(770, 160, 40, 30);

        progressBar_alineacion.setMaximum(20);
        getContentPane().add(progressBar_alineacion);
        progressBar_alineacion.setBounds(310, 290, 146, 14);

        progressBar_balanceo.setMaximum(20);
        getContentPane().add(progressBar_balanceo);
        progressBar_balanceo.setBounds(80, 290, 146, 14);

        progressBar_Frenos.setMaximum(20);
        getContentPane().add(progressBar_Frenos);
        progressBar_Frenos.setBounds(310, 130, 146, 14);

        progressBar_Cambio.setMaximum(20);
        getContentPane().add(progressBar_Cambio);
        progressBar_Cambio.setBounds(80, 130, 146, 14);

        lblareageneral.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblareageneral.setForeground(new java.awt.Color(0, 153, 153));
        lblareageneral.setText("Area Mecanica General");
        lblareageneral.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblareageneral.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        lblareageneral.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblareageneral);
        lblareageneral.setBounds(20, 70, 550, 390);

        lblareapintura.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblareapintura.setForeground(new java.awt.Color(0, 153, 153));
        lblareapintura.setText("Area  Pintura");
        lblareapintura.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblareapintura.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(lblareapintura);
        lblareapintura.setBounds(640, 70, 380, 140);

        jMenu4.setText("Inicio");

        item_registrar.setText("Registrar");
        item_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_registrarActionPerformed(evt);
            }
        });
        jMenu4.add(item_registrar);

        item_cerrar.setText("Cerrar");
        item_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_cerrarActionPerformed(evt);
            }
        });
        jMenu4.add(item_cerrar);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void item_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_registrarActionPerformed
        FrmMenu frmmenu = new FrmMenu(this, true, control);
        frmmenu.setVisible(true);
        control = frmmenu.getControl();
        System.out.println("Cerrada");

    }//GEN-LAST:event_item_registrarActionPerformed

    private void btnMecGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMecGenActionPerformed
        //Atender
        boolean fin = false;

        if (control != null) {
            do {
                Auto a = control.atender("Mecánica general");
                if (a != null) {
                    JLabel labelAuto = new JLabel("auto" + a.getPlaca());
                    labelAuto.setBounds(130, 430, 30, 30);
                    labelAuto.setBorder(new javax.swing.border.LineBorder(a.getColor(), 30, true));
                    labelAuto.setToolTipText("" + a.getPlaca());
                    getContentPane().add(labelAuto);

                    //MOVER EL AUTO AL SERVICIO QUE LE CORRESPONDE
                    System.out.println("a: " + a.getServicios().size());

                    switch (a.getServicios().get(0)) {
                        case "Revisión de frenos": {
                            int xinicial1 = 130;
                            int yinicial1 = 430;
                            int xmedio1 = 230;
                            int x1 = xinicial1;
                            int y1 = yinicial1;
                            int xfinal = 280;
                            int yfinal1 = 200;
                            
                            HiloMover clsHiloRevision = new HiloMover(x1, y1, xinicial1, yinicial1, xfinal, yfinal1, xmedio1, labelAuto);
                            int t=control.tiempo("Revisión de frenos");
                            System.out.println("tiempo: "+t);
                            clsHiloRevision.setTiempo(t);
                            clsHiloRevision.setBarra(progressBar_Frenos);
                            Thread hilo = new Thread(clsHiloRevision);
                            hilo.start();
                            break;
                        }
                        case "Alineación": {
                            int xinicial1 = 130;
                            int yinicial1 = 430;
                            int xmedio1 = 230;
                            int x1 = xinicial1;
                            int y1 = yinicial1;
                            int xfinal = 0;
                            int yfinal1 = 0;
                            xfinal = 270;//280;
                            yfinal1 = 360;
                            HiloMover clsHiloAlineacion = new HiloMover(x1, y1, xinicial1, yinicial1, xfinal, yfinal1, xmedio1, labelAuto);
                            int t=control.tiempo("Alineación");
                            System.out.println("Tiempo de alineacion: "+t);
                            clsHiloAlineacion.setTiempo(t);
                            clsHiloAlineacion.setBarra(progressBar_alineacion);
                            Thread hilo = new Thread(clsHiloAlineacion);
                            hilo.start();
                            break;
                        }
                        case "Balanceo": {
                            int xinicial1 = 130;
                            int yinicial1 = 430;
                            int xmedio1 = 230;
                            int x1 = xinicial1;
                            int y1 = yinicial1;
                            int xfinal = 0;
                            int yfinal1 = 0;
                            xfinal = 230;//280;
                            yfinal1 = 360;
                            HiloMover clsHiloBalanceo = new HiloMover(x1, y1, xinicial1, yinicial1, xfinal, yfinal1, xmedio1, labelAuto);
                            int t=control.tiempo("Balanceo");
                            System.out.println("Tiempo de balanceo: "+t);
                            clsHiloBalanceo.setTiempo(t);
                            clsHiloBalanceo.setBarra(progressBar_balanceo);
                            Thread hilo = new Thread(clsHiloBalanceo);
                            hilo.start();
                            break;
                        }
                        case "Cambio de aceite": {
                            int xinicial1 = 130;
                            int yinicial1 = 430;
                            int xmedio1 = 230;
                            int x1 = xinicial1;
                            int y1 = yinicial1;
                            int xfinal = 0;
                            int yfinal1 = 0;
                            xfinal = 230;//280;
                            yfinal1 = 200;
                            HiloMover clsHiloCambioAceite = new HiloMover(x1, y1, xinicial1, yinicial1, xfinal, yfinal1, xmedio1, labelAuto);
                            int t=control.tiempo("Cambio de aceite");
                            System.out.println("Tiempo de Cambio de aceite: "+t);
                            clsHiloCambioAceite.setTiempo(t);
                            clsHiloCambioAceite.setBarra(progressBar_Cambio);
                            Thread hilo = new Thread(clsHiloCambioAceite);
                            hilo.start();
                            break;
                        }
                    }
                } else {
                    fin = true;
                }
                try {
                    Thread.sleep(700);
                } catch (InterruptedException ex) {
                    System.out.println("Error al esperar para atender");
                }
                
            } while (!fin);
        } else {
            fin = true;
        }


    }//GEN-LAST:event_btnMecGenActionPerformed
    //******************************************************************** MARCELA CALDERÓN GIRALDO*********************************

    private void btnPinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinturaActionPerformed
        boolean error = false;
        if (control != null) {
            Auto a = control.atender("Pintura");
            if (a != null) {
                System.out.println("Existe el auto");
                JLabel labelAutoP = new JLabel("auto");
                labelAutoP.setBounds(640, 160, 30, 30);
                labelAutoP.setBorder(new javax.swing.border.LineBorder(a.getColor(), 30, true));
                labelAutoP.setToolTipText("" + a.getPlaca());
                getContentPane().add(labelAutoP);
//                //mover(labelAuto);

                int xinicial1 = 640;
                int yinicial1 = 160;
                int xmedio1 = 770;
                int xfinal1 = 770;//280;
                int yfinal1 = 100;//200;
                int x1 = xinicial1;
                int y1 = yinicial1;
                System.out.println("Entra al metodo pintura");
                HiloMover clsHilo = new HiloMover(x1, y1, xinicial1, yinicial1, xfinal1, yfinal1, xmedio1, labelAutoP);
                Thread hilo = new Thread(clsHilo);
                hilo.start();
                System.out.println("Estado hilo: " + hilo.getState());

            } else {
                error = true;
            }
        } else {
            error = true;
        }
        if (error) {
            JOptionPane.showMessageDialog(this, "No tiene carros para atender");
        }
    }//GEN-LAST:event_btnPinturaActionPerformed

    private void btnMecEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMecEspActionPerformed
        //Manejo excepxion parte leo

boolean error = false;
        if (control != null) {
            Auto a1 = control.atender("Mecánica especializada");

            if (a1 != null) {

                switch (a1.getServicios().getFirst()) {
                    case "Reparación de motor": {
                        JLabel labelAuto = new JLabel("auto");
                        labelAuto.setBounds(690, 320, 30, 30);
                        labelAuto.setBorder(new javax.swing.border.LineBorder(a1.getColor(), 30, true));
                        labelAuto.setToolTipText("" + a1.getPlaca());
                        getContentPane().add(labelAuto);
                        //mover(labelAuto);
                        int xinicial1 = 690;
                        int yinicial1 = 320;
                        int xmedio1 = 790;
                        int xfinal1 = 790;//280;
                        int yfinal1 = 350;//200;
                        int x1 = xinicial1;
                        int y1 = yinicial1;
                        HiloMover clsHilo = new HiloMover(x1, y1, xinicial1, yinicial1, xfinal1, yfinal1, xmedio1, labelAuto);
                        Thread hilo = new Thread(clsHilo);
                        hilo.start();
                        break;
                    }
                    case "Revisión y reparación del sistema eléctrico": {
                        JLabel labelAuto = new JLabel("auto");
                        labelAuto.setBounds(690, 320, 30, 30);
                        labelAuto.setBorder(new javax.swing.border.LineBorder(a1.getColor(), 30, true));
                        labelAuto.setToolTipText("" + a1.getPlaca());
                        getContentPane().add(labelAuto);
                        //mover(labelAuto);
                        int xinicial1 = 690;
                        int yinicial1 = 320;
                        int xmedio1 = 940;
                        int xfinal1 = 940;//280;
                        int yfinal1 = 350;//200;
                        int x1 = xinicial1;
                        int y1 = yinicial1;
                        HiloMover clsHilo = new HiloMover(x1, y1, xinicial1, yinicial1, xfinal1, yfinal1, xmedio1, labelAuto);
                        Thread hilo = new Thread(clsHilo);
                        hilo.start();
                        break;
                    }
                }

            } else {
                error = true;
            }
        } else {
            error = true;
        }
        if (error) {
            JOptionPane.showMessageDialog(this, "No tiene carros para atender");
        }

    }//GEN-LAST:event_btnMecEspActionPerformed

    private void item_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_cerrarActionPerformed
        dispose();

    }//GEN-LAST:event_item_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAtender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAtender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAtender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAtender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAtender().setVisible(true);
            }
        });
    }

    /**
     *
     * @param area 0=Pintura, 1=Mecanica general, 2= Mecanica especializada
     * @param color
     */
//Elminar metodo ESTE ESTE no otro es este*****************************************************MARCELA CALDERON
//    public static void nuevoCarro(int area, Color color) {
//        System.out.println("Crea nuevo carro");
//        if (area == 0) {
//            JLabel c1 = new JLabel();
//            c1.setBounds(20, 70, 20, 20);
//
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMecEsp;
    private javax.swing.JButton btnMecGen;
    private javax.swing.JButton btnPintura;
    private javax.swing.JMenuItem item_cerrar;
    private javax.swing.JMenuItem item_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JLabel lblaceite;
    private javax.swing.JLabel lblalineacio;
    private javax.swing.JLabel lblareageneral;
    private javax.swing.JLabel lblareapintura;
    private javax.swing.JLabel lblbalanceo;
    private javax.swing.JLabel lblelectrico;
    private javax.swing.JLabel lblensayo;
    private javax.swing.JLabel lblespecializada;
    private javax.swing.JLabel lblpintura;
    private javax.swing.JProgressBar progressBar_Cambio;
    private javax.swing.JProgressBar progressBar_Frenos;
    private javax.swing.JProgressBar progressBar_alineacion;
    private javax.swing.JProgressBar progressBar_balanceo;
    // End of variables declaration//GEN-END:variables
}
