/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVista;

import java.awt.Color;
import java.util.LinkedList;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import pkgControlador.Control;

/**
 *
 * @author Marcela
 */
public class FrmMenu extends javax.swing.JDialog {

    Control controlRec;
    LinkedList<String> servicios;
    Color colorAuto;
    boolean cerrar;

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu(java.awt.Frame parent, boolean modal, Control control) {
        super(parent, modal);
        initComponents();
        controlRec = new Control();
        servicios = new LinkedList<>();

        checkFrenos.setLabel("Revisión de frenos");
        checkaceite.setLabel("Cambio de aceite");
        checkalineacion.setLabel("Alineación");
        checkbalanceo.setLabel("Balanceo");

        checkmotor.setLabel("Reparación de motor");
        checkelectrico.setLabel("Revisión y reparación del sistema eléctrico");
        cerrar = false;
        if(control != null){
            controlRec=control;
        }
    }

    public String getComboAreas() {
        return cmbAreas.getToolTipText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbAreas = new javax.swing.JComboBox();
        txtplaca = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        checkFrenos = new java.awt.Checkbox();
        checkaceite = new java.awt.Checkbox();
        checkalineacion = new java.awt.Checkbox();
        checkbalanceo = new java.awt.Checkbox();
        checkmotor = new java.awt.Checkbox();
        checkelectrico = new java.awt.Checkbox();
        lblServiciosGeneral = new javax.swing.JLabel();
        lblServicosEspecializada = new javax.swing.JLabel();
        btncolor = new javax.swing.JToggleButton();
        btnguardar = new javax.swing.JButton();
        lblContenedorInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(535, 599));
        setResizable(false);
        getContentPane().setLayout(null);

        cmbAreas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pintura", "Mecánica general", "Mecánica especializada" }));
        cmbAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAreasActionPerformed(evt);
            }
        });
        getContentPane().add(cmbAreas);
        cmbAreas.setBounds(20, 170, 170, 20);

        txtplaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplacaActionPerformed(evt);
            }
        });
        getContentPane().add(txtplaca);
        txtplaca.setBounds(110, 80, 110, 20);
        getContentPane().add(txtmodelo);
        txtmodelo.setBounds(110, 110, 110, 20);

        jLabel1.setText("Placa:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 80, 40, 14);

        jLabel2.setText("Modelo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 110, 70, 14);

        jLabel3.setText("Color:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 140, 40, 14);

        jLabel4.setText("                      Servicios  Area escogida");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 290, 300, 20);

        checkFrenos.setEnabled(false);
        checkFrenos.setLabel("checkbox1");
        getContentPane().add(checkFrenos);
        checkFrenos.setBounds(30, 360, 160, 20);

        checkaceite.setEnabled(false);
        checkaceite.setLabel("checkbox2");
        getContentPane().add(checkaceite);
        checkaceite.setBounds(30, 380, 170, 20);

        checkalineacion.setEnabled(false);
        checkalineacion.setLabel("checkbox3");
        getContentPane().add(checkalineacion);
        checkalineacion.setBounds(30, 400, 170, 20);

        checkbalanceo.setEnabled(false);
        checkbalanceo.setLabel("checkbox4");
        getContentPane().add(checkbalanceo);
        checkbalanceo.setBounds(30, 420, 180, 20);

        checkmotor.setEnabled(false);
        checkmotor.setLabel("checkbox1");
        getContentPane().add(checkmotor);
        checkmotor.setBounds(220, 360, 230, 20);

        checkelectrico.setEnabled(false);
        checkelectrico.setLabel("checkbox3");
        getContentPane().add(checkelectrico);
        checkelectrico.setBounds(220, 380, 210, 20);

        lblServiciosGeneral.setText("Mecanica General");
        lblServiciosGeneral.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblServiciosGeneral);
        lblServiciosGeneral.setBounds(30, 330, 180, 150);

        lblServicosEspecializada.setText("Mecanica Especializada");
        lblServicosEspecializada.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblServicosEspecializada);
        lblServicosEspecializada.setBounds(220, 330, 150, 150);

        btncolor.setText("...");
        btncolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncolorActionPerformed(evt);
            }
        });
        getContentPane().add(btncolor);
        btncolor.setBounds(110, 140, 45, 23);

        btnguardar.setText("Guardar Cliente");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar);
        btnguardar.setBounds(143, 490, 110, 23);

        lblContenedorInfo.setText("Informacion Servicio y Automovil");
        lblContenedorInfo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblContenedorInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 3, true));
        getContentPane().add(lblContenedorInfo);
        lblContenedorInfo.setBounds(10, 40, 490, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtplacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplacaActionPerformed

    private void cmbAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAreasActionPerformed

        if (cmbAreas.getSelectedIndex() == 0) {
            checkFrenos.setEnabled(false);
            checkaceite.setEnabled(false);
            checkalineacion.setEnabled(false);
            checkbalanceo.setEnabled(false);
            checkmotor.setEnabled(false);
            checkelectrico.setEnabled(false);
            checkFrenos.setState(false);
            checkaceite.setState(false);
            checkalineacion.setState(false);
            checkbalanceo.setState(false);
            checkmotor.setState(false);
            checkelectrico.setState(false);

        } else if (cmbAreas.getSelectedIndex() == 1) {

            checkFrenos.setEnabled(true);
            checkaceite.setEnabled(true);
            checkalineacion.setEnabled(true);
            checkbalanceo.setEnabled(true);
            checkmotor.setEnabled(false);
            checkelectrico.setEnabled(false);
            checkmotor.setState(false);
            checkelectrico.setState(false);

        } else if (cmbAreas.getSelectedIndex() == 2) {
            checkmotor.setEnabled(true);
            checkelectrico.setEnabled(true);
            checkFrenos.setEnabled(false);
            checkaceite.setEnabled(false);
            checkalineacion.setEnabled(false);
            checkbalanceo.setEnabled(false);
            checkFrenos.setState(false);
            checkaceite.setState(false);
            checkalineacion.setState(false);
            checkbalanceo.setState(false);
        }
    }//GEN-LAST:event_cmbAreasActionPerformed

    private void btncolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncolorActionPerformed
        JColorChooser ventanaDecolores = new JColorChooser();
        Color color = ventanaDecolores.showDialog(null, "Seleccione el color del carro", Color.BLACK);
        colorAuto = color;
    }//GEN-LAST:event_btncolorActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        int area = cmbAreas.getSelectedIndex();
        if (area == 0) {
            servicios.add("Pintura");
        } else if (area == 1) {

            if (checkFrenos.getState()) {
                servicios.add("Revisión de frenos");
            }
            if (checkaceite.getState()) {
                servicios.add("Cambio de aceite");
            }
            if (checkbalanceo.getState()) {
                servicios.add("Alineación");
            }
            if (checkalineacion.getState()) {
                servicios.add("Balanceo");
            }

        } else if (area == 2) {
            if (checkmotor.getState()) {
                servicios.add("Reparación de motor");
            }
            if (checkelectrico.getState()) {
                servicios.add("Revisión y reparación del sistema eléctrico");
            }
        }

        boolean resultadoAdicional = controlRec.AdicionarAutos(txtplaca.getText(), txtmodelo.getText(), colorAuto, servicios, cmbAreas.getSelectedItem().toString());
        this.setVisible(false);


    }//GEN-LAST:event_btnguardarActionPerformed

    public Control getControl() {
        return controlRec;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btncolor;
    private javax.swing.JButton btnguardar;
    private java.awt.Checkbox checkFrenos;
    private java.awt.Checkbox checkaceite;
    private java.awt.Checkbox checkalineacion;
    private java.awt.Checkbox checkbalanceo;
    private java.awt.Checkbox checkelectrico;
    private java.awt.Checkbox checkmotor;
    private javax.swing.JComboBox cmbAreas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblContenedorInfo;
    private javax.swing.JLabel lblServiciosGeneral;
    private javax.swing.JLabel lblServicosEspecializada;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtplaca;
    // End of variables declaration//GEN-END:variables
}
